# Generated by Django 3.2.4 on 2021-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ManyToManyField(to='project.Projects'),
        ),
    ]
