# Generated by Django 3.2.4 on 2021-06-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210608_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='tasks',
            field=models.ManyToManyField(to='project.Tasks'),
        ),
    ]
