# Generated by Django 3.2.4 on 2021-06-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210608_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.TextField(),
        ),
    ]
